name: Go

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # Trigger on version tags
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name_suffix: linux-amd64-deb
            build_type: deb
          - os: ubuntu-latest
            name_suffix: linux-amd64
            build_type: binary
          - os: macos-latest
            name_suffix: macos-arm64
            build_type: binary
            goarch: arm64
          - os: macos-latest
            name_suffix: macos-amd64
            build_type: binary
            goarch: amd64

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            GOARCH=${{ matrix.goarch }} go build -v -o code-cadence .
          else
            go build -v -o code-cadence .
          fi

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "version_clean=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            # Use a valid Debian version format for dev builds
            COMMIT_SHORT=$(git rev-parse --short HEAD)
            echo "version=dev-${COMMIT_SHORT}" >> $GITHUB_OUTPUT
            echo "version_clean=0.0.0-dev-${COMMIT_SHORT}" >> $GITHUB_OUTPUT
          fi

      - name: Create Linux DEB package
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'deb'
        run: |
          # Install dpkg for DEB package creation
          sudo apt-get update
          sudo apt-get install -y dpkg-dev
          
          # Create package structure
          mkdir -p deb-package/usr/local/bin
          mkdir -p deb-package/usr/local/etc/code-cadence
          mkdir -p deb-package/DEBIAN
          
          # Copy binary
          cp code-cadence deb-package/usr/local/bin/
          
          # Copy env.example as .env in etc directory
          cp env.example deb-package/usr/local/etc/code-cadence/.env
          
          # Create control file for DEB package
          cat > deb-package/DEBIAN/control << EOF
          Package: code-cadence
          Version: ${{ steps.version.outputs.version_clean }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Egor Markin <egor.markin@gmail.com>
          Description: Code Cadence application
            A tool for managing code development workflows.
          EOF
          
          # Create postinst script to set proper permissions
          cat > deb-package/DEBIAN/postinst << EOF
          #!/bin/bash
          chmod +x /usr/local/bin/code-cadence
          chmod 644 /usr/local/etc/code-cadence/.env
          EOF
          chmod +x deb-package/DEBIAN/postinst
          
          # Build the DEB package
          dpkg-deb --build deb-package
          mkdir -p dist
          mv deb-package.deb dist/code-cadence-debian-amd64-${{ steps.version.outputs.version_clean }}.deb

      - name: Prepare Linux binary
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'binary'
        run: |
          mkdir -p dist
          cp code-cadence dist/

      - name: Prepare macOS binary
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p dist
          cp code-cadence dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('code-cadence-{0}-{1}', matrix.name_suffix, steps.version.outputs.version) }}
          path: dist/
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@5
        with:
          name: |
            code-cadence-macos-arm64-*
            code-cadence-macos-amd64-*
            code-cadence-linux-amd64-deb-*
            code-cadence-linux-amd64-*
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true
